"""venda na conta: cliente_id, paga_em, forma_pagamento anulavel

Revision ID: 1b919f72f683
Revises: 20ea22874dce
Create Date: 2026-07-09 21:04:02.467308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b919f72f683'
down_revision: Union[str, Sequence[str], None] = '20ea22874dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('paga_em', sa.DateTime(), nullable=True))
    op.alter_column('vendas', 'forma_pagamento',
               existing_type=postgresql.ENUM('PIX', 'DINHEIRO', 'DEBITO', 'CREDITO', name='formapagamento'),
               nullable=True)
    op.create_foreign_key(None, 'vendas', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendas_cliente_id_fkey', 'vendas', type_='foreignkey')
    op.alter_column('vendas', 'forma_pagamento',
               existing_type=postgresql.ENUM('PIX', 'DINHEIRO', 'DEBITO', 'CREDITO', name='formapagamento'),
               nullable=False)
    op.drop_column('vendas', 'paga_em')
    op.drop_column('vendas', 'cliente_id')
    # ### end Alembic commands ###
