"""timestamps com fuso horario

Revision ID: 1f3693142ae9
Revises: 69c198ad5f13
Create Date: 2026-07-21 19:37:09.275871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f3693142ae9'
down_revision: Union[str, Sequence[str], None] = '69c198ad5f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Os valores naive já gravados estão em UTC (o código sempre usou
    # datetime.now(timezone.utc)). O USING declara isso na conversão.
    op.alter_column('vendas', 'data_hora',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="data_hora AT TIME ZONE 'UTC'")
    op.alter_column('vendas', 'paga_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="paga_em AT TIME ZONE 'UTC'")
    op.alter_column('vendas', 'cancelada_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="cancelada_em AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendas', 'cancelada_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="cancelada_em AT TIME ZONE 'UTC'")
    op.alter_column('vendas', 'paga_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="paga_em AT TIME ZONE 'UTC'")
    op.alter_column('vendas', 'data_hora',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="data_hora AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###
