"""adiciona cancelada_em em vendas

Revision ID: 4ea16167ae86
Revises: 0b5a4edfb5ed
Create Date: 2026-07-07 14:09:14.887449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea16167ae86'
down_revision: Union[str, Sequence[str], None] = '0b5a4edfb5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('cancelada_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'cancelada_em')
    # ### end Alembic commands ###
