"""registrado_por na venda

Revision ID: 9d292fb07b83
Revises: c46958c9b4eb
Create Date: 2026-07-21 21:05:03.298640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d292fb07b83'
down_revision: Union[str, Sequence[str], None] = 'c46958c9b4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('registrado_por_id', sa.Integer(), nullable=False))
    op.create_foreign_key('vendas_registrado_por_id_fkey', 'vendas', 'usuarios', ['registrado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendas_registrado_por_id_fkey', 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'registrado_por_id')
    # ### end Alembic commands ###
