"""indices nas chaves estrangeiras

Revision ID: 9eb174df2cb2
Revises: 1d5f9ba460e4
Create Date: 2026-08-11 19:45:05.449217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb174df2cb2'
down_revision: Union[str, Sequence[str], None] = '1d5f9ba460e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_itens_venda_produto_id'), 'itens_venda', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_venda_id'), 'itens_venda', ['venda_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_vendedor_id'), 'itens_venda', ['vendedor_id'], unique=False)
    op.create_index(op.f('ix_produtos_vendedor_id'), 'produtos', ['vendedor_id'], unique=False)
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_registrado_por_id'), 'vendas', ['registrado_por_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_registrado_por_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_index(op.f('ix_produtos_vendedor_id'), table_name='produtos')
    op.drop_index(op.f('ix_itens_venda_vendedor_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_venda_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_produto_id'), table_name='itens_venda')
    # ### end Alembic commands ###
