"""adiciona forma_pagamento em vendas

Revision ID: a69499005200
Revises: 4ea16167ae86
Create Date: 2026-07-07 14:55:59.200845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69499005200'
down_revision: Union[str, Sequence[str], None] = '4ea16167ae86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    forma = sa.Enum('PIX', 'DINHEIRO', 'DEBITO', 'CREDITO', name='formapagamento')
    forma.create(op.get_bind(), checkfirst=True)
    op.add_column('vendas', sa.Column('forma_pagamento', sa.Enum('PIX', 'DINHEIRO', 'DEBITO', 'CREDITO', name='formapagamento', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'forma_pagamento')
    sa.Enum(name='formapagamento').drop(op.get_bind())
    # ### end Alembic commands ###
