"""adiciona email em usuarios

Revision ID: c46958c9b4eb
Revises: 2c0c6fcf55db
Create Date: 2026-07-21 20:49:42.545127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46958c9b4eb'
down_revision: Union[str, Sequence[str], None] = '2c0c6fcf55db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint('uq_usuarios_email', 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuarios_email', 'usuarios', type_='unique')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
